// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinderSurprise.MVP.View {
	
	
	public partial class UserControlSerieProperty {
		
		protected System.Web.UI.WebControls.Label LBL_ErrorMessage;
		
		protected System.Web.UI.WebControls.Literal LI_Serie_Name;
		
		protected System.Web.UI.WebControls.TextBox TB_Serie_Name;
		
		protected System.Web.UI.WebControls.Literal LI_Serie_Description;
		
		protected System.Web.UI.WebControls.TextBox TB_Serie_Description;
		
		protected System.Web.UI.WebControls.TextBox TB_PubYear;
		
		protected System.Web.UI.WebControls.Literal LI_Serie_Choose_Category;
		
		protected System.Web.UI.WebControls.DropDownList DDL_Serie_Choose_Category;
		
		protected System.Web.UI.WebControls.Button BTN_NewFigur;
		
		protected System.Web.UI.WebControls.Button BTN_NewSerie;
		
		protected System.Web.UI.WebControls.Button BTN_Save;
		
		protected System.Web.UI.WebControls.Button BTN_Cancel;
		
		protected System.Web.UI.WebControls.Button BTN_Delete;
	}
}
