// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinderSurprise.MVP.View {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.TreeView TV_Overview;
		
		protected System.Web.UI.WebControls.Menu Menu_TabMenu;
		
		protected System.Web.UI.WebControls.MultiView MV_Category;
		
		protected System.Web.UI.WebControls.View MV_Category_Properties;
		
		protected KinderSurprise.MVP.View.UserControlCategoryProperty UC_CategoryProperty;
		
		protected System.Web.UI.WebControls.MultiView MV_Serie;
		
		protected System.Web.UI.WebControls.View MV_Serie_Properties;
		
		protected KinderSurprise.MVP.View.UserControlSerieProperty UC_SerieProperty;
		
		protected System.Web.UI.WebControls.View MV_Serie_Store;
		
		protected System.Web.UI.WebControls.MultiView MV_Figur;
		
		protected System.Web.UI.WebControls.View MV_Figur_Properties;
		
		protected KinderSurprise.MVP.View.UserControlFigurProperty UC_FigurProperty;
		
		protected System.Web.UI.WebControls.View MV_Figur_Store;
	}
}
