// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinderSurprise.MVP.View {
	
	
	public partial class UserControlCategoryProperty {
		
		protected System.Web.UI.WebControls.Label LblErrorLabel;
		
		protected System.Web.UI.WebControls.Literal LI_Category_Name;
		
		protected System.Web.UI.WebControls.TextBox TbNameTextBox;
		
		protected System.Web.UI.WebControls.Literal LI_Category_Description;
		
		protected System.Web.UI.WebControls.TextBox TbDescriptionTextBox;
		
		protected System.Web.UI.WebControls.Button BTN_NewSerie;
		
		protected System.Web.UI.WebControls.Button BTN_NewCategory;
		
		protected System.Web.UI.WebControls.Button BTN_CategoryDelete;
		
		protected System.Web.UI.WebControls.Button BTN_CategoryUpdate;
		
		protected System.Web.UI.WebControls.Button BTN_CategoryCancel;
	}
}
