// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinderSurprise.MVP.View {
	
	
	public partial class UserControlFigurProperty {
		
		protected System.Web.UI.WebControls.Label LBL_ErrorMessage;
		
		protected System.Web.UI.WebControls.Literal LI_Serie_Name;
		
		protected System.Web.UI.WebControls.TextBox TB_Figur_Name;
		
		protected System.Web.UI.WebControls.Literal LI_Serie_Description;
		
		protected System.Web.UI.WebControls.TextBox TB_Figur_Description;
		
		protected System.Web.UI.WebControls.Literal LI_Serie_Price;
		
		protected System.Web.UI.WebControls.TextBox TB_Figur_Price;
		
		protected System.Web.UI.WebControls.Literal LI_Figur_Choose_Serie;
		
		protected System.Web.UI.WebControls.DropDownList DDL_Figur_Choose_Serie;
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.Button BTN_NewFigur;
		
		protected System.Web.UI.WebControls.Button BTN_Cancel;
		
		protected System.Web.UI.WebControls.Button BTN_Save;
		
		protected System.Web.UI.WebControls.Button BTN_Delete;
	}
}
