CREATE TABLE CHECK_UPDATES
(
	CREATION_DATE DATETIME NOT NULL,
	SCRIPT_NAME VARCHAR(100) NULL,
	SCRIPT_PURPOSE VARCHAR(4000) NULL
);

 
INSERT INTO CHECK_UPDATES (CREATION_DATE,SCRIPT_NAME,SCRIPT_PURPOSE) 
VALUES (NOW(),
	'2009 10 16 11 17 create table check_updates',
	'create table check_updates'
);
